### PR TITLE
Set default ncpus to os.cpu_count()

### PR DESCRIPTION
**Pull request by UmerHA**
This addresses issue #45

### CODE REVIEW

**Comment by chanhosuh** [comment]
Thanks for your submission.  Unfortunately we've been heavily reworking the codebase so the code now has a merge conflict.  However, a few comments:

* `ncpu = os.cpu_count() if os.cpu_count() is not None else 4` should probably have `1` as a fallback because if `os.cpu_count()` failed for whatever reason, there is no guarantee you have 4 cores.  In the unlikely event it failed, the user should probably just pass in a valid value for their system to get parallel processing.
* I don't like repeatedly calling functions like that.  I would name the result properly to avoid calling it again.
* I don't think we need a default arg value at the lower levels; just `autosim` ought to suffice for now.

**Comment by UmerHA** [comment]
Hey, I've adapted the PR to the new codebase & incorporated your feedback

**Comment by chanhosuh** [comment]
There are a lot of unnecessary whitespace changes to the docstrings in one file.  I've gone and changed them, since we would want to merge your contribution asap.  Had to do it on another branch though.

**Comment by chanhosuh** [comment]
Closed in favor of #62.  Don't worry, GitHub should still give you "credit" for your contributions, and we certainly appreciate it! :)

**Pull request closed without merging**
